const STATUS_CODE_OK = 200;
const STATUS_CODE_CREATED = 201;
const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_UNAUTHORIZED = 401;
const ERROR_CODE_FORBIDDEN = 403;
const ERROR_CODE_INTERNAL_SERVER_ERROR = 500;

module.exports = {
  STATUS_CODE_OK,
  STATUS_CODE_CREATED,
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_INTERNAL_SERVER_ERROR,
  ERROR_CODE_FORBIDDEN,
  ERROR_CODE_UNAUTHORIZED,
};
